#!/usr/bin/env bash

#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=24:gpus=1

#PBS -A starting_2024_024

#PBS -o ./condor_logs/logs_vsc/out_${PBS_JOBID}.txt
#PBS -e ./condor_logs/logs_vsc/err_${PBS_JOBID}.txt


cd /dodrio/scratch/projects/starting_2024_111/Balance

git pull origin vsc

source /dodrio/scratch/projects/starting_2024_024/env/Anaconda/etc/profile.d/conda.sh
conda activate /dodrio/scratch/projects/starting_2024_024/env/balance

which python
python -V
echo $PWD

accelerate launch main.py ${config} ${default_config}
