sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Balance/condor_logs/tier2/vsc_single_H100.slurm "./configs/SthSth/2mod/video_flow_Late_ShuffleGradEPIB_pre.json" "./configs/SthSth/default_config_vsc_sthsth_2mod.json"

sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora_synibfaster.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.01 10 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora_synibfaster.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.01 1 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora_synibfaster.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.01 0.1 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora_synibfaster.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.01 0.01 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.01 None 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.0001 0.001 None 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.001 0.01 None 8
sbatch  -A lp_biomed_mdv /scratch/leuven/350/vsc35057/projects/Synergy/condor_logs/tier2_2026/vsc_single_H100.slurm "./configs/ScienceQA/synprom_lora.json" "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" 0 0.001 0.001 None 8

python show.py --config "./configs/ScienceQA/synprom_lora_synibfaster.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.01 --l 10 --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora_synibfaster.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.01 --l 1 --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora_synibfaster.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.01 --l 0.1 --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora_synibfaster.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.01 --l 0.01 --batch_size 8

python show.py --config "./configs/ScienceQA/synprom_lora.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.01 --l None --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.0001 --wd 0.001 --l None --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.001 --wd 0.01 --l None --batch_size 8
python show.py --config "./configs/ScienceQA/synprom_lora.json" --default_config "./configs/ScienceQA/default_config_scienceqa_syn_tier2.json" --fold 0 --lr 0.001 --wd 0.001 --l None --batch_size 8