args_string='
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOneSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 0 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 1 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0003 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 0.0 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-5 --perturb gen --start_over --cls mlp --lib 0.01
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 1.0
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.1
python train.py --config ./configs/CREMA_D/synergy/nov/synprom_generatorVAEOtherSide.json --default_config ./configs/CREMA_D/default_config_cremad_res_syn.json --fold 2 --lr 0.0001 --wd 1e-4 --perturb gen --start_over --cls mlp --lib 0.01'

# Read the multi-line string into an array
IFS=$'\n' read -r -d '' -a args <<< "$args_string"$'\n'

echo "Starting Process"
for i in "${args[@]}"
do
    #transfer each one to this format /users/sista/kkontras/Documents/Balance/main_mcrema_MSLR.py,config-./configs/CREMA_D/vit/concat_multiloss_ShuffleGradFinalEPIB_test.json,default_config-./configs/CREMA_D/default_config_cremad.json,fold-0,lr-0.00005,wd-5e-6,l-0.1,l_diffsq-0,lib-0,clip-None,num_samples-32,reg_by-dist_pred_cjsd,pow-1,cls-linear,batch_size-8,contr_coeff-0,shuffle_type-rand,contr_type-label,temperature-None
    split_i=($i)
    make_string="/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py"
    for j in "${split_i[@]}"
        do
        if [[ "$j" == *--* ]]; then
            j="${j//--/}"
            make_string+=",$j"
        else
            make_string+="-$j"
        fi
    done
    echo $make_string
done


#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold0_regbydist_pred_3d_agree_l0.001_multil0.001_numsamples32_contrcoeff1.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold0_regbydist_pred_3d_disagree_l0.001_multil0.001_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_agree_l0.0001_multil0.01_numsamples32_contrcoeff1.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_disagree_l0.0001_multil0.01_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold0_regbydist_pred_3d_agree_l0.01_multil0.001_numsamples32_contrcoeff1.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold0_regbydist_pred_3d_disagree_l0.01_multil0.001_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_agree_l0.01_multil0.1_numsamples32_contrcoeff1.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_disagree_l0.01_multil0.1_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold1_regbydist_pred_3d_agree_l0.01_multil0.1_numsamples32_contrcoeff1.pth.tar      /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold1_regbydist_pred_3d_disagree_l0.01_multil0.1_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_agree_l0.1_multil0.1_numsamples32_contrcoeff1.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold2_regbydist_pred_3d_disagree_l0.1_multil0.1_numsamples32_contrcoeff1.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold1_regbydist_pred_3d_agree_l0.1_multil0.1_numsamples32_contrcoeff1.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/MOSEI_models/SuffleGradEPIB_pre_Tsai_fold1_regbydist_pred_3d_disagree_l0.1_multil0.1_numsamples32_contrcoeff1.pth.tar



#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold0_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold1_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/VAVL_multiloss_ShuffleGradFinalEPIB_pre_fold2_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00005_wd5e-6_linear_bs8.pth.tar

#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar

#rm -rfv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_multil0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#rm -rfv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_multil0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#rm -rfv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_multil0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar

#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_halfmultiloss_ShuffleGradFinalEP_trial2_pre_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_multil0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_halfmultiloss_ShuffleGradFinalEP_trial2_pre_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_multil0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_halfmultiloss_ShuffleGradFinalEP_trial2_pre_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_multil0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_doublemultiloss_ShuffleGradFinalEP_trial2_pre_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_multil2_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_doublemultiloss_ShuffleGradFinalEP_trial2_pre_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_multil2_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_doublemultiloss_ShuffleGradFinalEP_trial2_pre_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_multil2_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv  /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar   /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.1_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar



#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_fold0_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_fold0_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_fold1_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_fold1_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_singleloss_ShuffleGradFinalEP_fold2_regbydist_pred_cjsd_l0.1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/CREMAD_models/Res_multiloss_ShuffleGradFinalEP_fold2_regbydist_pred_cjsd_l0.1_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar



#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_fold1_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold1_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_fold2_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold2_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_fold3_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold3_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold1_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold1_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold2_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold2_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold3_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_fold3_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_pre_fold1_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold1_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_pre_fold2_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold2_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_pre_fold3_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold3_regbydist_pred_cjsd_l0.001_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold1_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold1_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold2_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold2_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#mv /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold3_regbydist_pred_cjsd_l0.001_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/UCF101_models/Res_ShuffleGradEP_multi_pre_fold3_regbydist_pred_cjsd_l0.001_multil1_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar


#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_fold0_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_fold1_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_fold2_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar


#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_pre_fold0_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_pre_fold1_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar
#cp /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_singleloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/AVE_models/Res_multiloss_ShuffleGradFinalEP_pre_fold2_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.0001_wd0.0001_linear_bs32.pth.tar


#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold0_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold1_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold2_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#
#
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold0_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold1_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_fold2_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#
#
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_pre_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold0_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_pre_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold1_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singleloss_ShuffleGradFinalEP_IB_pre_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold2_regbydist_pred_cjsd_l0.01_multil1_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#
#
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_pre_fold0_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold0_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_pre_fold1_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold1_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar
#cp  /scratch/leuven/350/vsc35057/models/AVE_models/vit_singlesingleloss_ShuffleGradFinalEP_IB_pre_fold2_regbydist_pred_cjsd_l0.01_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar /scratch/leuven/350/vsc35057/models/AVE_models/vit_multiloss_ShuffleGradFinalEP_IB_pre_fold2_regbydist_pred_cjsd_l0.01_multil0_ldiffsq0_lib1_numsamples32_pow1_contrcoeff1_strand_contrtypelabel_lr0.00001_wd0.0001_linear_bs8.pth.tar