Notification = Error
executable = /esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/condor_logs/condor/script_m.sh
initialdir = /esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/condor_logs/logs
Log = $(ClusterId)_$(Process).log
Output = $(ClusterId)_$(Process).out
Error = $(ClusterId)_$(Process).err
RequestCpus = 8
RequestMemory = 70G
RequestWalltime = 100000
Request_GPUs = 1
NiceUser = True
Requirements = ( GPUs_GlobalMemoryMb > 8000)  && (machine != "estragon.esat.kuleuven.be") && (machine != "vladimir.esat.kuleuven.be")
Queue Arguments from (
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.1
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.1
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.3
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.3
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.5
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.5
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.8
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-0.8
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-1.0
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-1.0
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_audio.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-2.0
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/jan/unimodal_video.json,default_config-./configs/CREMA_D/default_config_cremadplus_res_syn.json,fold-1,lr-0.0001,wd-0.0001,batch_size-64,cls-mlp,ironic_rate-2.0
)
