Notification = Error
executable = /esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/condor_logs/condor/script_m.sh
initialdir = /esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/condor_logs/logs
Log = $(ClusterId)_$(Process).log
Output = $(ClusterId)_$(Process).out
Error = $(ClusterId)_$(Process).err
RequestCpus = 8
RequestMemory = 70G
RequestWalltime = 100000
Request_GPUs = 1
NiceUser = True
Requirements = ( GPUs_GlobalMemoryMb > 8000) && (machine != "etrog.esat.kuleuven.be") && (machine != "stadius-nc-5.esat.kuleuven.be") && (machine != "vladimir.esat.kuleuven.be") && (machine != "vladimir.esat.kuleuven.be") && (machine != "estragon.esat.kuleuven.be")
Queue Arguments from (
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,lr-0.00001,wd-0.0001,cls-mlp,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.001,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-mean,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.001,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-zero,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.001,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-noise,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.01,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-mean,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.01,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-zero,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.01,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-noise,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.1,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-mean,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.1,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-zero,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-0.1,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-noise,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-1.0,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-mean,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-1.0,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-zero,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-1.0,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-noise,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-10,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-mean,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-10,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-zero,num_samples-32,start_over
/esat/smcdata/users/kkontras/Image_Dataset/no_backup/git/Synergy/train.py,config-./configs/CREMA_D/synergy/dec/synprom_IB_mask.json,default_config-./configs/CREMA_D/default_config_cremad_res_syn.json,fold-0,l-10,lr-0.00001,wd-0.0001,cls-mlp,perturb-mask,perturb_fill-noise,num_samples-32,start_over
)
